### ISSUE TITLE
Излишнее копирование

### ISSUE THREAD

**Issue by maked0n** [DariaFil/Rep1#4]
https://github.com/DariaFil/Rep1/blob/c16108b0a8906e4624e78d5e6dc38c36a932dba7/CCardReaderCreditcard.cpp#L12

**Comment by DariaFil** [comment]
Данный метод в новом коммите будет добавлен только в абстрактного предка и переопределен только для декоратора-шифровальщика

**Comment by maked0n** [comment]
ответ не понял  
как это связано с излишним копированием?

**Comment by DariaFil** [comment]
Тогда я не понимаю, в чём заключается излишнее копирование? Я подумала, что в копировании метода во всех потомков, когда можно написать его только для предков

**Comment by maked0n** [comment]
У тебя был метод:
```
string CCardReaderPassport::post_data(string data) {
	return data;
}
```
Он не выполняет ничего полезного, но зато:
1. аллоцирует data.size() байт памяти
2. копирует data.data() в аллоцированную память
3. еще раз аллоцирует data.size() байт памяти
4. еще раз копирует data.data() в аллоцированную память

**Comment by DariaFil** [comment]
Теперь я поняла, постараюсь изменить этот метод или вообще избавиться от него

**Comment by maked0n** [comment]
Можно просто хотя бы передавать строки (и вообще все большие объекты) по ссылкам на константные объекты. Это касается не только этого метода, а вообще всего кода проекта.

**Comment by maked0n** [comment]
обычно если метод принимает ссылку в аргументах - это значит, что внутри метода объект по ссылке будет меняться  
так что в твоем случае уместно передавать ссылку на константный объект

**Comment by DariaFil** [comment]
Спасибо, исправлю в кратчайшие сроки

**Comment by DariaFil** [comment]
Но ведь в методе decryptor я изменяю строку, поэтому туда я не могу передавать ссылку на константный объект. А в post_data тогда тоже не могу передать ссылку на константный объект, потому что в классе CCardtReaderCryptDecorator этот метод передаёт строку в decryptor и она там изменяется.

**Comment by maked0n** [comment]
если не можешь - ок
просто учти этот факт на будущее
