### ISSUE TITLE
Уместность Factory

### ISSUE THREAD

**Issue by maked0n** [DariaFil/Rep1#6]
Не ясна мотивация использования паттерна Factory method в проекте с универсальной картой.

**Comment by DariaFil** [comment]
Действительно, объекты довольно несложные, поэтому можно обойтись и без фабрик. Изначально я считала, что если есть объекты одного общего предка и одного интерфейса, то удобнее делать для них различные фабрики, чтобы в них отразить незначительные различия объектов

**Comment by maked0n** [comment]
> если есть объекты одного общего предка и одного интерфейса, то удобнее делать для них различные фабрики  
такую ситуацию можно представить, но все же у тебя слишком простые объекты для этого  
думаю, фабрика тут лишняя

**Comment by DariaFil** [comment]
Фабрики убраны
